Config = {}

-- All editor tuning lives here so position editing can be adjusted without
-- touching the NUI or client logic.
Config.Editor = {
    positionSliderMin = -0.75,
    positionSliderMax = 0.75,
    positionHardLimit = 2.0,
    positionSteps = { 0.001, 0.005, 0.020 },
    rotationMin = -180.0,
    rotationMax = 180.0,
    rotationSteps = { 1.0, 5.0, 15.0 },
    historyLimit = 30,
    previewAssetTimeout = 2000,
    previewRetryDelay = 250,
    saveTimeout = 10000,
    renderDistance = 50.0,
    reconciliationInterval = 3000,
}

Config.WeaponList = {
    {name = 'Pistol',                   label = 'WEAPON_PISTOL',                object = 'w_pi_pistol'},
    {name = 'Pistol MK-2',              label = 'WEAPON_PISTOL_MK2',            object = 'w_pi_pistol'},
    {name = 'Combat Pistol',            label = 'WEAPON_COMBATPISTOL',          object = 'w_pi_combatpistol'},
    {name = 'SNS Pistol',               label = 'WEAPON_SNSPISTOL',             object = 'w_pi_sns_pistol'},
    {name = 'SNS Pistol MK-2',          label = 'WEAPON_SNSPISTOL_MK2',         object = 'w_pi_sns_pistol'},
    {name = 'Vintage Pistol',           label = 'WEAPON_VINTAGEPISTOL',         object = 'w_pi_vintage_pistol'},
    {name = 'Heavy Pistol',             label = 'WEAPON_HEAVYPISTOL',           object = 'w_pi_heavypistol'},
    {name = 'Pistol .50',               label = 'WEAPON_PISTOL50',              object = 'w_pi_pistol50'},
    {name = 'AP Pistol',                label = 'WEAPON_APPISTOL',              object = 'w_pi_appistol'},
    {name = 'Heavy Revolver',           label = 'WEAPON_REVOLVER',              object = 'w_pi_combatpistol'},
    {name = 'Heavy Revolver MK-2',      label = 'WEAPON_REVOLVER_MK2',          object = 'w_pi_combatpistol'},
    {name = 'Double Action Revolver',   label = 'WEAPON_DOUBLEACTION',          object = 'w_pi_combatpistol'},
    {name = 'Ceramic Pistol',           label = 'WEAPON_CERAMICPISTOL',         object = 'w_pi_combatpistol'},
    {name = 'Flare Gun',                label = 'WEAPON_FLAREGUN',              object = 'w_pi_flaregun'},
    {name = 'Micro SMG',                label = 'WEAPON_MICROSMG',              object = 'w_sb_microsmg'},
    {name = 'Mini SMG',                 label = 'WEAPON_MINISMG',               object = 'w_sb_microsmg'},
    {name = 'SMG',                      label = 'WEAPON_SMG',                   object = 'w_sb_smg'},
    {name = 'SMG MK-2',                 label = 'WEAPON_SMG_MK2',               object = 'w_sb_smg'},
    {name = 'Assault SMG',              label = 'WEAPON_ASSAULTSMG',            object = 'w_sb_assaultsmg'},
    {name = 'Combat PDW',               label = 'WEAPON_COMBATPDW',             object = 'w_sb_smg'},
    {name = 'Assault Rifle',            label = 'WEAPON_ASSAULTRIFLE',          object = 'w_ar_assaultrifle'},
    {name = 'Assault Rifle MK-2',       label = 'WEAPON_ASSAULTRIFLE_MK2',      object = 'w_ar_assaultrifle'},
    {name = 'Carbine Rifle',            label = 'WEAPON_CARBINERIFLE',          object = 'w_ar_carbinerifle'},
    {name = 'Carbine Rifle MK-2',       label = 'WEAPON_CARBINERIFLE_MK2',      object = 'w_ar_carbinerifle'},
    {name = 'Compact Rifle',            label = 'WEAPON_COMPACTRIFLE',          object = 'w_ar_carbinerifle'},
    {name = 'Advanced Rifle',           label = 'WEAPON_ADVANCEDRIFLE',         object = 'w_ar_advancedrifle'},
    {name = 'Special Carbine',          label = 'WEAPON_SPECIALCARBINE',        object = 'w_ar_specialcarbine'},
    {name = 'Special Carbine MK-2',     label = 'WEAPON_SPECIALCARBINE_MK2',    object = 'w_ar_specialcarbine'},
    {name = 'Bullpup Rifle',            label = 'WEAPON_BULLPUPRIFLE',          object = 'w_ar_bullpuprifle'},
    {name = 'Bullpup Rifle MK-2',       label = 'WEAPON_BULLPUPRIFLE_MK2',      object = 'w_ar_bullpuprifle'},
    {name = 'Sniper Rifle',             label = 'WEAPON_SNIPERRIFLE',           object = 'w_sr_sniperrifle'},
    {name = 'Heavy Sniper',             label = 'WEAPON_HEAVYSNIPER',           object = 'w_sr_heavysniper'},
    {name = 'Heavy Sniper MK-2',        label = 'WEAPON_HEAVYSNIPER_MK2',       object = 'w_sr_heavysniper'},
    {name = 'Marksman Rifle',           label = 'WEAPON_MARKSMANRIFLE',         object = 'w_sr_marksmanrifle'},
    {name = 'Marksman Rifle MK-2',      label = 'WEAPON_MARKSMANRIFLE_MK2',     object = 'w_sr_marksmanrifle'},
    {name = 'Pump Shotgun',             label = 'WEAPON_PUMPSHOTGUN',           object = 'w_sg_pumpshotgun'},
    {name = 'Pump Shotgun MK-2',        label = 'WEAPON_PUMPSHOTGUN_MK2',       object = 'w_sg_pumpshotgun'},
    {name = 'Sawn-Off Shotgun',         label = 'WEAPON_SAWNOFFSHOTGUN',        object = 'w_sg_sawnoff'},
    {name = 'Assault Shotgun',          label = 'WEAPON_ASSAULTSHOTGUN',        object = 'w_sg_assaultshotgun'},
    {name = 'Bullpup Shotgun',          label = 'WEAPON_BULLPUPSHOTGUN',        object = 'w_sg_bullpupshotgun'},
    {name = 'Heavy Shotgun',            label = 'WEAPON_HEAVYSHOTGUN',          object = 'w_sg_heavyshotgun'},
    {name = 'Musket',                   label = 'WEAPON_MUSKET',                object = 'w_sg_pumpshotgun'},
    {name = 'MG',                       label = 'WEAPON_MG',                    object = 'w_mg_mg'},
    {name = 'Combat MG',                label = 'WEAPON_COMBATMG',              object = 'w_mg_combatmg'},
    {name = 'Combat MG MK-2',           label = 'WEAPON_COMBATMG_MK2',          object = 'w_mg_combatmg'},
    {name = 'Gusenberg',                label = 'WEAPON_GUSENBERG',             object = 'w_sb_gusenberg'},
    {name = 'Less Launcher',            label = 'WEAPON_LESSLAUNCHER',          object = 'w_lr_launcher'},
    {name = 'VF-17',                    label = 'WEAPON_VF17',                  object = 'w_pi_combatpistol'},
    {name = 'VF-18',                    label = 'WEAPON_VF18',                  object = 'w_pi_vf18'},
    {name = 'VF-9C',                    label = 'WEAPON_VF9C',                  object = 'w_pi_vf9c'},
    {name = 'ZN509',                    label = 'WEAPON_ZN509',                 object = 'w_pi_zn509'},
    {name = 'Tactical Carbine',         label = 'WEAPON_TCARBINE',              object = 'w_ar_carbinerifle'},
    {name = 'Beanbag',                  label = 'WEAPON_BEANBAG',               object = 'w_sg_pumpshotgun'},
    {name = 'Battle Rifle',             label = 'WEAPON_BATTLERIFLE',           object = 'w_ar_assaultrifle'},
    {name = 'Tactical SMG',             label = 'WEAPON_TECPISTOL',             object = 'w_sb_microsmg'},
    {name = 'Snowball Launcher',        label = 'WEAPON_SNOWLAUNCHER',          object = 'w_lr_launcher'},
    {name = 'Vom Feuer Carbine',         label = 'WEAPON_VFCARBINE',            object = 'w_ar_vfcarbine'},
    {name = 'Vom Feuer Special Carbine', label = 'WEAPON_SPCARBINE',            object = 'w_ar_spcarbine'},
    {name = 'Shrewsbury E870',           label = 'WEAPON_M870_SHOTGUN',         object = 'w_sg_M870shotgun'},
    {name = 'Shrewsbury 870SO',          label = 'WEAPON_870SO_SHOTGUN',        object = 'w_sg_870so'},
    {name = 'VF PRO SMG',                label = 'WEAPON_VFPROSMG',             object = 'w_sb_prosmg'},
    {name = 'H&L 50E',                   label = 'WEAPON_HL50E',                object = 'w_pi_hl50e'},
    {name = 'H&L CP',                    label = 'WEAPON_HLCP',                 object = 'w_pi_hlcp'},
}

Config.Bones = {
    {label = 'Lưng',        value = 24817, name = 'bone_back'},
    {label = 'Hông',      value = 11816, name = 'bone_pelvis'},
    {label = 'Đùi Trái',  value = 58271, name = 'bone_ltight'},
    {label = 'Đùi Phải', value = 51826, name = 'bone_rtight'},
    {label = 'Bàn Chân Trái',   value = 14201, name = 'bone_lfoot'},
    {label = 'Bàn Chân Phải',  value = 52301, name = 'bone_rfoot'}
}
