CREATE TABLE IF NOT EXISTS `police_arrests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `officer_identifier` VARCHAR(80) NOT NULL,
  `officer_name` VARCHAR(120) NOT NULL,
  `officer_badge` VARCHAR(32) NULL,
  `faction_tag` VARCHAR(32) NOT NULL,
  `target_identifier` VARCHAR(80) NOT NULL,
  `target_name` VARCHAR(120) NOT NULL,
  `reason` TEXT NOT NULL,
  `base_minutes` INT NOT NULL,
  `extra_minutes` INT NOT NULL DEFAULT 0,
  `final_minutes` INT NOT NULL,
  `fine_amount` INT NOT NULL DEFAULT 0,
  `cell_index` INT NOT NULL DEFAULT 1,
  `arrested_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_police_arrests_target_time` (`target_identifier`, `arrested_at`),
  KEY `idx_police_arrests_officer_time` (`officer_identifier`, `arrested_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `police_bolos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('person','vehicle') NOT NULL,
  `target_identifier` VARCHAR(80) NULL,
  `target_name` VARCHAR(120) NULL,
  `plate` VARCHAR(32) NULL,
  `title` VARCHAR(160) NOT NULL,
  `reason` TEXT NOT NULL,
  `priority` ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `status` ENUM('active','resolved','expired','cancelled') NOT NULL DEFAULT 'active',
  `created_by_identifier` VARCHAR(80) NOT NULL,
  `created_by_name` VARCHAR(120) NOT NULL,
  `faction_tag` VARCHAR(32) NOT NULL,
  `expires_at` DATETIME NULL,
  `resolved_at` DATETIME NULL,
  `resolved_by_identifier` VARCHAR(80) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_police_bolos_active_type` (`status`, `type`, `expires_at`),
  KEY `idx_police_bolos_identifier` (`target_identifier`, `status`),
  KEY `idx_police_bolos_plate` (`plate`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
