const $=s=>document.querySelector(s),app=$('#app');let data={},selected='',rolling=false,pending=false,result=null,timer=null,offset=0;
const post=(n,b={})=>fetch('https://'+GetParentResourceName()+'/'+n,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
const icon=r=>r.image||(r.type==='item'&&r.item?'https://cfx-nui-ox_inventory/web/images/'+r.item+'.png':'');
const color=r=>data.rarities?.[r]?.color||'#999',rarity=r=>data.rarities?.[r]?.label||r;
function visual(r){if(icon(r))return '<img src="'+icon(r)+'" onerror="this.style.display=\'none\'">';if(r.type==="prime")return '<svg class="prime-icon" viewBox="0 0 64 64" aria-hidden="true"><path d="M9 47h46l4-29-15 12-12-20-12 20L5 18l4 29Zm2 5h42v5H11v-5Z" fill="currentColor"></path></svg>';return '<i>◆</i>'}
function card(r,c){return '<div class="'+c+'" style="--c:'+color(r.rarity)+'">'+visual(r)+'<div><b>'+r.name+'</b><small>'+rarity(r.rarity)+'</small></div></div>'}
function random(){const a=data.cases[selected].rewards;let n=Math.random()*100;for(const r of a){n-=Number(r.chance)||0;if(n<=0)return r}return a[a.length-1]}
function seed(){if(rolling)return;const e=$('#reel');e.style.transition='none';e.style.transform='translateX(0)';e.innerHTML=Array.from({length:10},()=>card(random(),'roll-card')).join('')}
function caseButton(id){const c=data.cases[id],count=data.counts?.[id]||{},src=c.image||c.inventoryIcon||("https://cfx-nui-ox_inventory/web/images/"+c.boxItem+".png");return `<button class="case `+(id===selected?"active":"")+`" data-id="`+id+`"><span class="case-art"><img src="`+src+`" onerror="this.style.display=\'none\'"></span><span class="case-copy"><b>`+c.label+`</b><small>`+(count.boxes||0)+` hòm · `+(c.keyAmount||1)+` chìa</small></span><span class="case-arrow">›</span></button>`}
function render(){const ids=Object.keys(data.cases||{});if(!data.cases?.[selected])selected=ids[0]||'';const c=data.cases?.[selected];if(!c)return;$('#logo').src=data.logo||'';document.querySelector("#cases").innerHTML=ids.map(caseButton).join("");$('#caseName').textContent=c.label;$('#desc').textContent=c.description;const count=data.counts?.[selected]||{};$('#boxes').textContent=count.boxes||0;$('#keys').textContent=(count.keys||0)+' / '+(c.keyAmount||1);$('#costText').textContent='Cần 1 hòm và '+(c.keyAmount||1)+' chìa';const p=data.states?.[selected]?.pity||0,m=c.pity?.at||1;$('#pityText').textContent=c.pity?.enabled?'Bảo hiểm '+rarity(c.pity.minimumRarity):'Không có bảo hiểm';$('#pityNumber').textContent=c.pity?.enabled?p+' / '+m:'';$('#pityBar').style.width=Math.min(100,p/m*100)+'%';$('#lootCount').textContent=c.rewards.length;$('#rewards').innerHTML=c.rewards.map(r=>card(r,'reward')).join('');document.querySelectorAll('.case').forEach(b=>b.onclick=()=>{if(rolling||pending)return;selected=b.dataset.id;render()});$('#open').disabled=rolling||pending;seed()}
function show(){if(!result)return;clearTimeout(timer);cancelAnimationFrame(tickFrame);if(reelAnimation){try{reelAnimation.commitStyles()}catch(e){}reelAnimation.cancel();reelAnimation=null}rolling=pending=false;$('#skip').classList.add('hidden');$('#open').disabled=false;const w=$('#win');w.style.setProperty('--c',color(result.rarity));w.style.setProperty('--glow',color(result.rarity)+'24');$('#winVisual').innerHTML=visual(result);$('#winName').textContent=result.name;$('#winMeta').textContent=rarity(result.rarity)+(result.extra?.plate?' · '+result.extra.plate:'');w.classList.remove('hidden')}
let reelAnimation=null,tickFrame=0,lastTick=-1,audioCtx=null;
function bestRare(){const a=[...data.cases[selected].rewards];a.sort((x,y)=>(data.rarities?.[y.rarity]?.rank||0)-(data.rarities?.[x.rarity]?.rank||0));return a[0]}
function tick(){try{audioCtx=audioCtx||new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=920;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.025);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.026)}catch(e){}}
function watchTicks(){if(!rolling)return;const reel=document.querySelector("#reel"),tr=getComputedStyle(reel).transform;let x=0;if(tr&&tr!=="none")x=Math.abs(new DOMMatrixReadOnly(tr).m41);const n=Math.floor((x+document.querySelector("#roulette").clientWidth/2)/208);if(n!==lastTick){lastTick=n;tick()}tickFrame=requestAnimationFrame(watchTicks)}
function animate(r){result=r;rolling=true;pending=false;document.querySelector("#open").disabled=true;document.querySelector("#skip").classList.remove("hidden");const list=Array.from({length:58},random),idx=50,rare=bestRare();list[idx]=r;if(Math.random()<.72&&rare.id!==r.id)list[idx-1]=rare;if(Math.random()<.28&&rare.id!==r.id)list[idx+1]=rare;const e=document.querySelector("#reel");e.innerHTML=list.map(x=>card(x,"roll-card")).join("");e.style.transition="none";e.style.transform="translate3d(0,0,0)";offset=idx*208-(document.querySelector("#roulette").clientWidth/2-99)+(Math.random()*70-35);const duration=11500+Math.floor(Math.random()*2500);e.getBoundingClientRect();requestAnimationFrame(()=>{e.style.transition="transform "+duration+"ms cubic-bezier(.035,.82,.025,1)";e.style.transform="translate3d(-"+offset+"px,0,0)"});lastTick=-1;timer=setTimeout(show,duration+100)}
function skip(){if(!rolling||!result)return;clearTimeout(timer);cancelAnimationFrame(tickFrame);if(reelAnimation)reelAnimation.cancel();const e=document.querySelector("#reel");e.style.transition="transform .3s ease-out";e.style.transform="translateX(-"+offset+"px)";document.querySelector("#skip").classList.add("hidden");timer=setTimeout(show,340)}
function closeNui(){if(rolling)return;clearTimeout(timer);cancelAnimationFrame(tickFrame);if(reelAnimation){reelAnimation.cancel();reelAnimation=null}rolling=false;pending=false;result=null;document.querySelector("#skip").classList.add("hidden");document.querySelector("#win").classList.add("hidden");app.classList.add("hidden");post("close")}
window.addEventListener('message',e=>{const m=e.data;if(m.action==='open'){app.classList.remove('hidden');post('refresh')}else if(m.action==='close')app.classList.add('hidden');else if(m.action==='data'){data=m.payload||{};render()}else if(m.action==='spinFailed'){pending=false;document.querySelector('#open').disabled=false}else if(m.action==='result'&&m.payload?.reward&&!app.classList.contains('hidden'))animate(m.payload.reward)});
$('#open').onclick=()=>{if(rolling||pending)return;pending=true;$('#open').disabled=true;setTimeout(()=>{if(pending){pending=false;document.querySelector("#open").disabled=false}},1800);post('spin',{banner:selected}).catch(()=>{pending=false;$('#open').disabled=false})};$('#skip').onclick=skip;document.querySelector("#close").onclick=closeNui;$('#again').onclick=()=>{$('#win').classList.add('hidden');result=null;seed()};document.addEventListener('keyup',e=>{if(e.key==="Escape")closeNui()});
