CREATE TABLE IF NOT EXISTS `lv_idcards` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `identifier`  VARCHAR(60)  NOT NULL,
  `firstname`   VARCHAR(50)  NOT NULL,
  `lastname`    VARCHAR(50)  NOT NULL,
  `dob`         VARCHAR(20)  NOT NULL,
  `address`     VARCHAR(120) NOT NULL,
  `sex`         CHAR(1)      NOT NULL DEFAULT 'M',
  `hair`        VARCHAR(10)  NOT NULL DEFAULT 'BLK',
  `eyes`        VARCHAR(10)  NOT NULL DEFAULT 'BRN',
  `height`      VARCHAR(12)  NOT NULL DEFAULT '',
  `weight`      VARCHAR(12)  NOT NULL DEFAULT '',
  `nationality` VARCHAR(50)  DEFAULT NULL,
  `photo_url`   VARCHAR(512) NOT NULL,
  `issue_date`  DATE         NOT NULL,
  `expire_date` DATE         NOT NULL,
  `status`      ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `approved_by` VARCHAR(60)  DEFAULT NULL,
  `driver_license` VARCHAR(20) DEFAULT 'NONE',
  `weapon_license` VARCHAR(20) DEFAULT 'NONE',
  `created_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_identifier` (`identifier`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
